version: "{build}"
clone_depth: 5

build: off

install:
  - SET PATH=C:\Ruby%RUBY_FOLDER_VER%\bin;%PATH%
  - bundle install --retry 5 --jobs=%NUMBER_OF_PROCESSORS% --clean --path vendor\bundle

environment:
  global:
    CC: gcc
  matrix:
    - RUBY_FOLDER_VER: "25"
    - RUBY_FOLDER_VER: "25-x64"
    - RUBY_FOLDER_VER: "24"
    - RUBY_FOLDER_VER: "23"

test_script:
  - ruby --version
  - gem --version
  - bundler --version
  - bundle exec rake test

cache:
  # If one of the files after the right arrow changes, cache will be skipped
  - 'vendor\bundle -> appveyor.yml,Gemfile,sassc.gemspec'
